#
# /*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# + Copyright 2024. NHN Academy Corp. All rights reserved.
# + * While every precaution has been taken in the preparation of this resource,  assumes no
# + responsibility for errors or omissions, or for damages resulting from the use of the information
# + contained herein
# + No part of this resource may be reproduced, stored in a retrieval system, or transmitted, in any
# + form or by any means, electronic, mechanical, photocopying, recording, or otherwise, without the
# + prior written permission.
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
#

spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/nhn_exam_102
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nhn_exam_102
    password: xV2paoph!

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect